export GENIN="/Users/benayoun/Softwares/STAR-2.7.7a/genomes/MM10"

########  Map Single end samples
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447101_VAT_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447101_VAT_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447103_VAT_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447103_VAT_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447105_VAT_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447105_VAT_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447107_VAT_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447107_VAT_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447109_VAT_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447109_VAT_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447111_VAT_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447111_VAT_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447113_VAT_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447113_VAT_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447115_Spleen_macrophages_3m_male.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447115_Spleen_macrophages_3m_male_STAR_                    
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447116_Spleen_macrophages_3m_male.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447116_Spleen_macrophages_3m_male_STAR_                    
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447119_Spleen_macrophages_24m_male.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447119_Spleen_macrophages_24m_male_STAR_                   
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447120_Spleen_macrophages_24m_male.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447120_Spleen_macrophages_24m_male_STAR_                   
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447122_Spleen_macrophages_24m_male.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447122_Spleen_macrophages_24m_male_STAR_                   
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2447124_Spleen_macrophages_24m_male.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2447124_Spleen_macrophages_24m_male_STAR_                   
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589843_BAM_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589843_BAM_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589844_BMM_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589844_BMM_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589845_BAM_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589845_BAM_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589846_BMM_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589846_BMM_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589847_BAM_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589847_BAM_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589848_BMM_macrophages_24m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589848_BMM_macrophages_24m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589849_BAM_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589849_BAM_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589850_BMM_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589850_BMM_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589851_BAM_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589851_BAM_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589852_BMM_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589852_BMM_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589853_BAM_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589853_BAM_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2589854_BMM_macrophages_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2589854_BMM_macrophages_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2593464_Microglia_brain_22m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2593464_Microglia_brain_22m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2593465_Microglia_brain_22m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2593465_Microglia_brain_22m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2593466_Microglia_brain_22m_male.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2593466_Microglia_brain_22m_male_STAR_                      
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2593467_Microglia_brain_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2593467_Microglia_brain_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2593468_Microglia_brain_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2593468_Microglia_brain_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2593469_Microglia_brain_3m_male.fastq.gz                         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2593469_Microglia_brain_3m_male_STAR_                       
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2857711_Nerve_Macrophage_3m_female_Rep_1.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2857711_Nerve_Macrophage_3m_female_Rep_1_STAR_              
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM2857712_Nerve_Macrophage_3m_female_Rep_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2857712_Nerve_Macrophage_3m_female_Rep_2_STAR_              
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3895604_Nerve_Macrophage_15m_female_Rep_1.fastq.gz               --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3895604_Nerve_Macrophage_15m_female_Rep_1_STAR_             
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3895605_Nerve_Macrophage_15m_female_Rep_2.fastq.gz               --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3895605_Nerve_Macrophage_15m_female_Rep_2_STAR_             
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232352_SkM_Macrophages_18m_NA.fastq.gz                          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232352_SkM_Macrophages_18m_NA_STAR_                        
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232353_SkM_Macrophages_18m_NA.fastq.gz                          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232353_SkM_Macrophages_18m_NA_STAR_                        
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232354_SkM_Macrophages_18m_NA.fastq.gz                          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232354_SkM_Macrophages_18m_NA_STAR_                        
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232355_SkM_Macrophages_18m_NA.fastq.gz                          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232355_SkM_Macrophages_18m_NA_STAR_                        
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232356_SkM_Macrophages_18m_NA.fastq.gz                          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232356_SkM_Macrophages_18m_NA_STAR_                        
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232357_SkM_Macrophages_4m_NA.fastq.gz                           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232357_SkM_Macrophages_4m_NA_STAR_                         
#STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232358_SkM_Macrophages_4m_NA.fastq.gz                           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232358_SkM_Macrophages_4m_NA_STAR_                         
########STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232359_SkM_Macrophages_4m_NA.fastq.gz                           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232359_SkM_Macrophages_4m_NA_STAR_                         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/ReDL/GSM4232359_SkM_Macrophages_4m_NA_reDL.fastq.gz                           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232359_SkM_Macrophages_4m_NA_STAR_                         
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232360_SkM_Macrophages_4m_NA.fastq.gz                           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232360_SkM_Macrophages_4m_NA_STAR_                         
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4232361_SkM_Macrophages_4m_NA.fastq.gz                           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4232361_SkM_Macrophages_4m_NA_STAR_                         
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4681350_eWAT_phagocytic_SVF_2m_male.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4681350_eWAT_phagocytic_SVF_2m_male_STAR_                   
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4681352_eWAT_phagocytic_SVF_20m_male.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4681352_eWAT_phagocytic_SVF_20m_male_STAR_                  
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4681354_eWAT_phagocytic_SVF_2m_male.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4681354_eWAT_phagocytic_SVF_2m_male_STAR_                   
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4681356_eWAT_phagocytic_SVF_20m_male.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4681356_eWAT_phagocytic_SVF_20m_male_STAR_                  
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984872_Callus_Macrophages_24m_males_O_Cont6.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984872_Callus_Macrophages_24m_males_O_Cont6_STAR_        
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984873_Callus_Macrophages_24m_males_O_Cont7.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984873_Callus_Macrophages_24m_males_O_Cont7_STAR_        
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984874_Callus_Macrophages_24m_males_O_Cont8.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984874_Callus_Macrophages_24m_males_O_Cont8_STAR_        
# #STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984875_Callus_Macrophages_24m_males_O_Cont9.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984875_Callus_Macrophages_24m_males_O_Cont9_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984876_Callus_Macrophages_24m_males_O_Cont10.fastq.gz         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984876_Callus_Macrophages_24m_males_O_Cont10_STAR_       
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984877_Callus_Macrophages_24m_males_O_Cont11.fastq.gz         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984877_Callus_Macrophages_24m_males_O_Cont11_STAR_       
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984878_Callus_Macrophages_24m_males_O_Cont12.fastq.gz         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984878_Callus_Macrophages_24m_males_O_Cont12_STAR_       
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984879_Callus_Macrophages_24m_males_O_Cont13.fastq.gz         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984879_Callus_Macrophages_24m_males_O_Cont13_STAR_       
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984880_Callus_Macrophages_24m_males_O_Cont14.fastq.gz         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984880_Callus_Macrophages_24m_males_O_Cont14_STAR_       
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984881_Callus_Macrophages_24m_males_O_Cont15.fastq.gz         --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984881_Callus_Macrophages_24m_males_O_Cont15_STAR_       
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984882_Callus_Macrophages_3m_males_Y_Cont6.fastq.gz           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984882_Callus_Macrophages_3m_males_Y_Cont6_STAR_         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984883_Callus_Macrophages_3m_males_Y_Cont7.fastq.gz           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984883_Callus_Macrophages_3m_males_Y_Cont7_STAR_         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984884_Callus_Macrophages_3m_males_Y_Cont8.fastq.gz           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984884_Callus_Macrophages_3m_males_Y_Cont8_STAR_         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984885_Callus_Macrophages_3m_males_Y_Cont9.fastq.gz           --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984885_Callus_Macrophages_3m_males_Y_Cont9_STAR_         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984886_Callus_Macrophages_3m_males_Y_Cont10.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984886_Callus_Macrophages_3m_males_Y_Cont10_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984887_Callus_Macrophages_3m_males_Y_Cont11.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984887_Callus_Macrophages_3m_males_Y_Cont11_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984888_Callus_Macrophages_3m_males_Y_Cont12.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984888_Callus_Macrophages_3m_males_Y_Cont12_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984889_Callus_Macrophages_3m_males_Y_Cont13.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984889_Callus_Macrophages_3m_males_Y_Cont13_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984890_Callus_Macrophages_3m_males_Y_Cont14.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984890_Callus_Macrophages_3m_males_Y_Cont14_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984891_Callus_Macrophages_3m_males_Y_Cont15.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984891_Callus_Macrophages_3m_males_Y_Cont15_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SAMN16984892_Callus_Macrophages_3m_males_Y_Cont16.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SAMN16984892_Callus_Macrophages_3m_males_Y_Cont16_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SRX3995437_BMDM_6m_males_Ames_Dwarf_dfdf.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SRX3995437_BMDM_6m_males_Ames_Dwarf_dfdf_STAR_                 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SRX3995438_BMDM_6m_males_Ames_Dwarf_dfdf.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SRX3995438_BMDM_6m_males_Ames_Dwarf_dfdf_STAR_                 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SRX3995439_BMDM_6m_males_Ames_Dwarf_dfdf.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SRX3995439_BMDM_6m_males_Ames_Dwarf_dfdf_STAR_                 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SRX3995441_BMDM_6m_males_Ames_CTL_Ndf.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SRX3995441_BMDM_6m_males_Ames_CTL_Ndf_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SRX3995448_BMDM_6m_males_Ames_CTL_Ndf.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SRX3995448_BMDM_6m_males_Ames_CTL_Ndf_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/SRX3995451_BMDM_6m_males_Ames_CTL_Ndf.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix SRX3995451_BMDM_6m_males_Ames_CTL_Ndf_STAR_    
#                      
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945726_Alveolar_Macrophages_4m_Males.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945726_Alveolar_Macrophages_4m_Males_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945727_Alveolar_Macrophages_4m_Males.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945727_Alveolar_Macrophages_4m_Males_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945728_Alveolar_Macrophages_4m_Males.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945728_Alveolar_Macrophages_4m_Males_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945734_Alveolar_Macrophages_18m_Males.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945734_Alveolar_Macrophages_18m_Males_STAR_                   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945735_Alveolar_Macrophages_18m_Males.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945735_Alveolar_Macrophages_18m_Males_STAR_                   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945736_Alveolar_Macrophages_18m_Males.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945736_Alveolar_Macrophages_18m_Males_STAR_                   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945737_Alveolar_Macrophages_18m_Males.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945737_Alveolar_Macrophages_18m_Males_STAR_                   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945738_Alveolar_Macrophages_18m_Males.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945738_Alveolar_Macrophages_18m_Males_STAR_                   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945865_Alveolar_Macrophages_AM_4m_control_Males.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945865_Alveolar_Macrophages_AM_4m_control_Males_STAR_         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945867_Alveolar_Macrophages_AM_4m_control_Males.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945867_Alveolar_Macrophages_AM_4m_control_Males_STAR_         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945869_Alveolar_Macrophages_AM_4m_control_Males.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945869_Alveolar_Macrophages_AM_4m_control_Males_STAR_         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945871_Alveolar_Macrophages_AM_4m_control_Males.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945871_Alveolar_Macrophages_AM_4m_control_Males_STAR_         
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945873_Alveolar_Macrophages_AM_4m_metformin_60d_Males.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945873_Alveolar_Macrophages_AM_4m_metformin_60d_Males_STAR_   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945875_Alveolar_Macrophages_AM_4m_metformin_60d_Males.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945875_Alveolar_Macrophages_AM_4m_metformin_60d_Males_STAR_   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945877_Alveolar_Macrophages_AM_4m_metformin_60d_Males.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945877_Alveolar_Macrophages_AM_4m_metformin_60d_Males_STAR_   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945879_Alveolar_Macrophages_AM_4m_metformin_60d_Males.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945879_Alveolar_Macrophages_AM_4m_metformin_60d_Males_STAR_   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945881_Alveolar_Macrophages_AM_4m_metformin_60d_Males.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945881_Alveolar_Macrophages_AM_4m_metformin_60d_Males_STAR_   
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945883_Alveolar_Macrophages_AM_18m_control_Males.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945883_Alveolar_Macrophages_AM_18m_control_Males_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945885_Alveolar_Macrophages_AM_18m_control_Males.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945885_Alveolar_Macrophages_AM_18m_control_Males_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945887_Alveolar_Macrophages_AM_18m_control_Males.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945887_Alveolar_Macrophages_AM_18m_control_Males_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945889_Alveolar_Macrophages_AM_18m_control_Males.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945889_Alveolar_Macrophages_AM_18m_control_Males_STAR_        
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945891_Alveolar_Macrophages_AM_18m_metformin_60d_Males.fastq.gz --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945891_Alveolar_Macrophages_AM_18m_metformin_60d_Males_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945893_Alveolar_Macrophages_AM_18m_metformin_60d_Males.fastq.gz --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945893_Alveolar_Macrophages_AM_18m_metformin_60d_Males_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3945895_Alveolar_Macrophages_AM_18m_metformin_60d_Males.fastq.gz --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945895_Alveolar_Macrophages_AM_18m_metformin_60d_Males_STAR_  
# 
#                      
#                                                               
# ########  Map paired end samples                  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3555595_ImmGen_Macrophages_Peritoneal_Cavity_female_2_months_old_1.fastq.gz ../FASTQ/GSM3555595_ImmGen_Macrophages_Peritoneal_Cavity_female_2_months_old_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3555595_ImmGen_Macrophages_Peritoneal_Cavity_female_2_months_old_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3555596_ImmGen_Macrophages_Peritoneal_Cavity_male_2_months_old_1.fastq.gz ../FASTQ/GSM3555596_ImmGen_Macrophages_Peritoneal_Cavity_male_2_months_old_2.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3555596_ImmGen_Macrophages_Peritoneal_Cavity_male_2_months_old_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3555597_ImmGen_Macrophages_Peritoneal_Cavity_female_6_months_old_1.fastq.gz ../FASTQ/GSM3555597_ImmGen_Macrophages_Peritoneal_Cavity_female_6_months_old_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3555597_ImmGen_Macrophages_Peritoneal_Cavity_female_6_months_old_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3555598_ImmGen_Macrophages_Peritoneal_Cavity_male_6_months_old_1.fastq.gz ../FASTQ/GSM3555598_ImmGen_Macrophages_Peritoneal_Cavity_male_6_months_old_2.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3555598_ImmGen_Macrophages_Peritoneal_Cavity_male_6_months_old_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3555593_ImmGen_Macrophages_Peritoneal_Cavity_female_17_months_old_1.fastq.gz ../FASTQ/GSM3555593_ImmGen_Macrophages_Peritoneal_Cavity_female_17_months_old_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3555593_ImmGen_Macrophages_Peritoneal_Cavity_female_17_months_old_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3555594_ImmGen_Macrophages_Peritoneal_Cavity_male_20_months_old_1.fastq.gz ../FASTQ/GSM3555594_ImmGen_Macrophages_Peritoneal_Cavity_male_20_months_old_2.fastq.gz      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3555594_ImmGen_Macrophages_Peritoneal_Cavity_male_20_months_old_STAR_  
# 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557702_Alveolar_Macrophages_3m_NA_1.fastq.gz ../FASTQ/GSM3557702_Alveolar_Macrophages_3m_NA_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557702_Alveolar_Macrophages_3m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557703_Alveolar_Macrophages_22m_NA_1.fastq.gz ../FASTQ/GSM3557703_Alveolar_Macrophages_22m_NA_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557703_Alveolar_Macrophages_22m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557704_Alveolar_Macrophages_22m_NA_1.fastq.gz ../FASTQ/GSM3557704_Alveolar_Macrophages_22m_NA_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557704_Alveolar_Macrophages_22m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557705_Alveolar_Macrophages_3m_NA_1.fastq.gz ../FASTQ/GSM3557705_Alveolar_Macrophages_3m_NA_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557705_Alveolar_Macrophages_3m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557706_Alveolar_Macrophages_22m_NA_1.fastq.gz ../FASTQ/GSM3557706_Alveolar_Macrophages_22m_NA_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557706_Alveolar_Macrophages_22m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557707_Alveolar_Macrophages_3m_NA_1.fastq.gz ../FASTQ/GSM3557707_Alveolar_Macrophages_3m_NA_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557707_Alveolar_Macrophages_3m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557708_Alveolar_Macrophages_22m_NA_1.fastq.gz ../FASTQ/GSM3557708_Alveolar_Macrophages_22m_NA_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557708_Alveolar_Macrophages_22m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557709_Alveolar_Macrophages_22m_NA_1.fastq.gz ../FASTQ/GSM3557709_Alveolar_Macrophages_22m_NA_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557709_Alveolar_Macrophages_22m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557710_Alveolar_Macrophages_3m_NA_1.fastq.gz ../FASTQ/GSM3557710_Alveolar_Macrophages_3m_NA_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557710_Alveolar_Macrophages_3m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557711_Alveolar_Macrophages_22m_NA_1.fastq.gz ../FASTQ/GSM3557711_Alveolar_Macrophages_22m_NA_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557711_Alveolar_Macrophages_22m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557713_Alveolar_Macrophages_3m_NA_1.fastq.gz ../FASTQ/GSM3557713_Alveolar_Macrophages_3m_NA_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557713_Alveolar_Macrophages_3m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3557715_Alveolar_Macrophages_22m_NA_1.fastq.gz ../FASTQ/GSM3557715_Alveolar_Macrophages_22m_NA_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3557715_Alveolar_Macrophages_22m_NA_STAR_  
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823683_Microglia_2m_male_1.fastq.gz ../FASTQ/GSM3823683_Microglia_2m_male_2.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823683_Microglia_2m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823684_Microglia_2m_male_1.fastq.gz ../FASTQ/GSM3823684_Microglia_2m_male_2.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823684_Microglia_2m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823685_Microglia_2m_male_1.fastq.gz ../FASTQ/GSM3823685_Microglia_2m_male_2.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823685_Microglia_2m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823686_Microglia_2m_male_1.fastq.gz ../FASTQ/GSM3823686_Microglia_2m_male_2.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823686_Microglia_2m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823687_Microglia_2m_male_1.fastq.gz ../FASTQ/GSM3823687_Microglia_2m_male_2.fastq.gz                      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823687_Microglia_2m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823688_Microglia_2m_female_1.fastq.gz ../FASTQ/GSM3823688_Microglia_2m_female_2.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823688_Microglia_2m_female_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823689_Microglia_2m_female_1.fastq.gz ../FASTQ/GSM3823689_Microglia_2m_female_2.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823689_Microglia_2m_female_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823690_Microglia_2m_female_1.fastq.gz ../FASTQ/GSM3823690_Microglia_2m_female_2.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823690_Microglia_2m_female_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823691_Microglia_2m_female_1.fastq.gz ../FASTQ/GSM3823691_Microglia_2m_female_2.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823691_Microglia_2m_female_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823692_Microglia_2m_female_1.fastq.gz ../FASTQ/GSM3823692_Microglia_2m_female_2.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823692_Microglia_2m_female_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823693_Microglia_2m_female_1.fastq.gz ../FASTQ/GSM3823693_Microglia_2m_female_2.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823693_Microglia_2m_female_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823714_Microglia_12m_female_1.fastq.gz ../FASTQ/GSM3823714_Microglia_12m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823714_Microglia_12m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823715_Microglia_12m_female_1.fastq.gz ../FASTQ/GSM3823715_Microglia_12m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823715_Microglia_12m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823716_Microglia_12m_female_1.fastq.gz ../FASTQ/GSM3823716_Microglia_12m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823716_Microglia_12m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823717_Microglia_12m_female_1.fastq.gz ../FASTQ/GSM3823717_Microglia_12m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823717_Microglia_12m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823718_Microglia_12m_female_1.fastq.gz ../FASTQ/GSM3823718_Microglia_12m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823718_Microglia_12m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823719_Microglia_12m_female_1.fastq.gz ../FASTQ/GSM3823719_Microglia_12m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823719_Microglia_12m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823720_Microglia_12m_female_1.fastq.gz ../FASTQ/GSM3823720_Microglia_12m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823720_Microglia_12m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823721_Microglia_12m_male_1.fastq.gz ../FASTQ/GSM3823721_Microglia_12m_male_2.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823721_Microglia_12m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823722_Microglia_12m_male_1.fastq.gz ../FASTQ/GSM3823722_Microglia_12m_male_2.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823722_Microglia_12m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823723_Microglia_12m_male_1.fastq.gz ../FASTQ/GSM3823723_Microglia_12m_male_2.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823723_Microglia_12m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823747_Microglia_24m_female_1.fastq.gz ../FASTQ/GSM3823747_Microglia_24m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823747_Microglia_24m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823748_Microglia_24m_female_1.fastq.gz ../FASTQ/GSM3823748_Microglia_24m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823748_Microglia_24m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823749_Microglia_24m_female_1.fastq.gz ../FASTQ/GSM3823749_Microglia_24m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823749_Microglia_24m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823750_Microglia_24m_male_1.fastq.gz ../FASTQ/GSM3823750_Microglia_24m_male_2.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823750_Microglia_24m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823751_Microglia_24m_female_1.fastq.gz ../FASTQ/GSM3823751_Microglia_24m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823751_Microglia_24m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823752_Microglia_24m_female_1.fastq.gz ../FASTQ/GSM3823752_Microglia_24m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823752_Microglia_24m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823753_Microglia_24m_female_1.fastq.gz ../FASTQ/GSM3823753_Microglia_24m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823753_Microglia_24m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823754_Microglia_24m_female_1.fastq.gz ../FASTQ/GSM3823754_Microglia_24m_female_2.fastq.gz                --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823754_Microglia_24m_female_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823755_Microglia_24m_male_1.fastq.gz ../FASTQ/GSM3823755_Microglia_24m_male_2.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823755_Microglia_24m_male_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM3823756_Microglia_24m_male_1.fastq.gz ../FASTQ/GSM3823756_Microglia_24m_male_2.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3823756_Microglia_24m_male_STAR_                                       
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065891_Microglia_WT_2m1_Males_1.fastq.gz ../FASTQ/GSM4065891_Microglia_WT_2m1_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065891_Microglia_WT_2m1_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065892_Microglia_WT_2m2_Males_1.fastq.gz ../FASTQ/GSM4065892_Microglia_WT_2m2_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065892_Microglia_WT_2m2_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065893_Microglia_WT_2m3_Males_1.fastq.gz ../FASTQ/GSM4065893_Microglia_WT_2m3_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065893_Microglia_WT_2m3_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065894_Microglia_WT_4m1_Males_1.fastq.gz ../FASTQ/GSM4065894_Microglia_WT_4m1_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065894_Microglia_WT_4m1_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065895_Microglia_WT_4m2_Males_1.fastq.gz ../FASTQ/GSM4065895_Microglia_WT_4m2_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065895_Microglia_WT_4m2_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065896_Microglia_WT_4m3_Males_1.fastq.gz ../FASTQ/GSM4065896_Microglia_WT_4m3_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065896_Microglia_WT_4m3_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065897_Microglia_WT_6m1_Males_1.fastq.gz ../FASTQ/GSM4065897_Microglia_WT_6m1_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065897_Microglia_WT_6m1_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065898_Microglia_WT_6m2_Males_1.fastq.gz ../FASTQ/GSM4065898_Microglia_WT_6m2_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065898_Microglia_WT_6m2_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065899_Microglia_WT_6m3_Males_1.fastq.gz ../FASTQ/GSM4065899_Microglia_WT_6m3_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065899_Microglia_WT_6m3_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065900_Microglia_WT_9m1_Males_1.fastq.gz ../FASTQ/GSM4065900_Microglia_WT_9m1_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065900_Microglia_WT_9m1_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065901_Microglia_WT_9m2_Males_1.fastq.gz ../FASTQ/GSM4065901_Microglia_WT_9m2_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065901_Microglia_WT_9m2_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065902_Microglia_WT_9m3_Males_1.fastq.gz ../FASTQ/GSM4065902_Microglia_WT_9m3_Males_2.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065902_Microglia_WT_9m3_Males_STAR_ 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065903_Microglia_WT_12m1_Males_1.fastq.gz ../FASTQ/GSM4065903_Microglia_WT_12m1_Males_2.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065903_Microglia_WT_12m1_Males_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065904_Microglia_WT_12m2_Males_1.fastq.gz ../FASTQ/GSM4065904_Microglia_WT_12m2_Males_2.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065904_Microglia_WT_12m2_Males_STAR_
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4065905_Microglia_WT_12m3_Males_1.fastq.gz ../FASTQ/GSM4065905_Microglia_WT_12m3_Males_2.fastq.gz          --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4065905_Microglia_WT_12m3_Males_STAR_
# 
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4314353_lung_macrophages_2.5m.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4314353_lung_macrophages_2.5m_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4314354_lung_macrophages_2.5m.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4314354_lung_macrophages_2.5m_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4314355_lung_macrophages_2.5m.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4314355_lung_macrophages_2.5m_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4314356_lung_macrophages_2.5m.fastq.gz                  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4314356_lung_macrophages_2.5m_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4314357_lung_macrophages_18m.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4314357_lung_macrophages_18m_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4314358_lung_macrophages_18m.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4314358_lung_macrophages_18m_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4314359_lung_macrophages_18m.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4314359_lung_macrophages_18m_STAR_                    
# STAR --genomeDir $GENIN --readFilesIn  ../FASTQ/GSM4314360_lung_macrophages_18m.fastq.gz                   --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM4314360_lung_macrophages_18m_STAR_                    
# 
##################################################################################################################################################################

##################################################################################################################################################################
# 2025-02-07

NEWFQ="/Volumes/BB_HQ_1/Immune_sex_dimorphism_Aging/Macrophage_Aging_Public/RNA-seq/FASTQ/NEW"


#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686814_03months_ZT0_1_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686814_03months_ZT0_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686815_03months_ZT0_2_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686815_03months_ZT0_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686816_03months_ZT0_3_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686816_03months_ZT0_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686817_03months_ZT4_1_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686817_03months_ZT4_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686818_03months_ZT4_2_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686818_03months_ZT4_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686819_03months_ZT4_3_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686819_03months_ZT4_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686820_03months_ZT8_1_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686820_03months_ZT8_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686821_03months_ZT8_2_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686821_03months_ZT8_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686822_03months_ZT8_3_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686822_03months_ZT8_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686823_03months_ZT12_1_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686823_03months_ZT12_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686824_03months_ZT12_2_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686824_03months_ZT12_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686825_03months_ZT12_3_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686825_03months_ZT12_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686826_03months_ZT16_1_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686826_03months_ZT16_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686827_03months_ZT16_2_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686827_03months_ZT16_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686828_03months_ZT16_3_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686828_03months_ZT16_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686829_03months_ZT20_1_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686829_03months_ZT20_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686830_03months_ZT20_2_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686830_03months_ZT20_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686831_03months_ZT20_3_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686831_03months_ZT20_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686832_03months_ZT24_1_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686832_03months_ZT24_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686833_03months_ZT24_2_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686833_03months_ZT24_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686834_03months_ZT24_3_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686834_03months_ZT24_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686835_20months_ZT0_1_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686835_20months_ZT0_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686836_20months_ZT0_2_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686836_20months_ZT0_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686837_20months_ZT0_3_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686837_20months_ZT0_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686838_20months_ZT4_1_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686838_20months_ZT4_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686839_20months_ZT4_2_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686839_20months_ZT4_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686840_20months_ZT4_3_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686840_20months_ZT4_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686841_20months_ZT8_1_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686841_20months_ZT8_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686842_20months_ZT8_2_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686842_20months_ZT8_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686843_20months_ZT8_3_Males_Peritoneal_Macrophages_pooled.fastq.gz             --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686843_20months_ZT8_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686844_20months_ZT12_1_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686844_20months_ZT12_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686845_20months_ZT12_2_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686845_20months_ZT12_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686846_20months_ZT12_3_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686846_20months_ZT12_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686847_20months_ZT16_1_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686847_20months_ZT16_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686848_20months_ZT16_2_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686848_20months_ZT16_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686849_20months_ZT16_3_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686849_20months_ZT16_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686850_20months_ZT20_1_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686850_20months_ZT20_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686851_20months_ZT20_2_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686851_20months_ZT20_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686852_20months_ZT20_3_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686852_20months_ZT20_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686853_20months_ZT24_1_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686853_20months_ZT24_1_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686854_20months_ZT24_2_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686854_20months_ZT24_2_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3686855_20months_ZT24_3_Males_Peritoneal_Macrophages_pooled.fastq.gz            --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3686855_20months_ZT24_3_Males_Peritoneal_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3945726_04_months_MixedSex_Alveolar_Macrophages_pooled.fastq.gz                 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945726_04_months_MixedSex_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3945727_04_months_MixedSex_Alveolar_Macrophages_pooled.fastq.gz                 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945727_04_months_MixedSex_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3945728_04_months_MixedSex_Alveolar_Macrophages_pooled.fastq.gz                 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945728_04_months_MixedSex_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3945729_04_months_MixedSex_Alveolar_Macrophages_pooled.fastq.gz                 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945729_04_months_MixedSex_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3945734_18_months_MixedSex_Alveolar_Macrophages_pooled.fastq.gz                 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945734_18_months_MixedSex_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3945735_18_months_MixedSex_Alveolar_Macrophages_pooled.fastq.gz                 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945735_18_months_MixedSex_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3945736_18_months_MixedSex_Alveolar_Macrophages_pooled.fastq.gz                 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945736_18_months_MixedSex_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM3945737_18_months_MixedSex_Alveolar_Macrophages_pooled.fastq.gz                 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM3945737_18_months_MixedSex_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5729052_06months_NA_Alveolar_Macrophages_pooled.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5729052_06months_NA_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5729053_18months_NA_Alveolar_Macrophages_pooled.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5729053_18months_NA_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5729054_18months_NA_Alveolar_Macrophages_pooled.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5729054_18months_NA_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5729055_18months_NA_Alveolar_Macrophages_pooled.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5729055_18months_NA_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5729061_06months_NA_Alveolar_Macrophages_pooled.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5729061_06months_NA_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5729064_06months_NA_Alveolar_Macrophages_pooled.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5729064_06months_NA_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5729066_06months_NA_Alveolar_Macrophages_pooled.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5729066_06months_NA_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5729067_18months_NA_Alveolar_Macrophages_pooled.fastq.gz                        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5729067_18months_NA_Alveolar_Macrophages_STAR_     
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5989996_02months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5989996_02months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5989997_02months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM5989997_02months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
####STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5989998_02months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5989998_02months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5989999_02months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5989999_02months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5990000_10months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5990000_10months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5990001_10months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5990001_10months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5990002_10months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5990002_10months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5990003_10months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5990003_10months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM6211369_03months_Males_Skeletal_Muscle_Macrophages.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM6211369_03months_Males_Skeletal_Muscle_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM6211370_03months_Males_Skeletal_Muscle_Macrophages.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM6211370_03months_Males_Skeletal_Muscle_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM6211371_26months_Males_Skeletal_Muscle_Macrophages.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM6211371_26months_Males_Skeletal_Muscle_Macrophages_STAR_     
###STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM6211372_26months_Males_Skeletal_Muscle_Macrophages.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM6211372_26months_Males_Skeletal_Muscle_Macrophages_STAR_     


#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5984045_03months_Female_Skin_Wound_Macrophages_1.fastq.gz $NEWFQ/GSM5984045_03months_Female_Skin_Wound_Macrophages_2.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5984045_03months_Female_Skin_Wound_Macrophages_STAR_
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5984046_03months_Female_Skin_Wound_Macrophages_1.fastq.gz $NEWFQ/GSM5984046_03months_Female_Skin_Wound_Macrophages_2.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5984046_03months_Female_Skin_Wound_Macrophages_STAR_
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5984047_03months_Female_Skin_Wound_Macrophages_1.fastq.gz $NEWFQ/GSM5984047_03months_Female_Skin_Wound_Macrophages_2.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5984047_03months_Female_Skin_Wound_Macrophages_STAR_
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5984048_24months_Female_Skin_Wound_Macrophages_1.fastq.gz $NEWFQ/GSM5984048_24months_Female_Skin_Wound_Macrophages_2.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5984048_24months_Female_Skin_Wound_Macrophages_STAR_
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5984049_24months_Female_Skin_Wound_Macrophages_1.fastq.gz $NEWFQ/GSM5984049_24months_Female_Skin_Wound_Macrophages_2.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5984049_24months_Female_Skin_Wound_Macrophages_STAR_
#STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5984050_24months_Female_Skin_Wound_Macrophages_1.fastq.gz $NEWFQ/GSM5984050_24months_Female_Skin_Wound_Macrophages_2.fastq.gz       --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM5984050_24months_Female_Skin_Wound_Macrophages_STAR_


STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5989997_02months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM5989997_02months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5989999_02months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM5989999_02months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5990000_10months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM5990000_10months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5990001_10months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM5990001_10months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5990002_10months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM5990002_10months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM5990003_10months_Female_Spleen_Red_Pulp_Macrophages.fastq.gz                    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM5990003_10months_Female_Spleen_Red_Pulp_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM6211369_03months_Males_Skeletal_Muscle_Macrophages.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM6211369_03months_Males_Skeletal_Muscle_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM6211370_03months_Males_Skeletal_Muscle_Macrophages.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM6211370_03months_Males_Skeletal_Muscle_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM6211371_26months_Males_Skeletal_Muscle_Macrophages.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM6211371_26months_Males_Skeletal_Muscle_Macrophages_STAR_     
STAR --genomeDir $GENIN --readFilesIn  $NEWFQ/GSM6211372_26months_Males_Skeletal_Muscle_Macrophages.fastq.gz                     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM Unsorted --outFileNamePrefix GSM6211372_26months_Males_Skeletal_Muscle_Macrophages_STAR_     

